# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-28 05:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elbaul', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PropertyImage',
            new_name='imagenDeGaleria',
        ),
    ]
