# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-28 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elbaul', '0002_auto_20170428_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagendegaleria',
            name='imagen',
            field=models.ImageField(upload_to='imagenes/%Y%m%d/'),
        ),
    ]
