# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-04 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elbaul', '0003_auto_20170428_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeria',
            name='descripcion',
            field=models.TextField(default="Baul's Images!"),
        ),
    ]
