# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-05 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elbaul', '0004_galeria_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('nombre', models.CharField(max_length=60)),
                ('email', models.CharField(blank=True, max_length=60)),
                ('comment', models.TextField(max_length=1000)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='galeria',
            name='descripcion',
            field=models.TextField(default="Baul's Images!", max_length=123),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='nombre',
            field=models.TextField(max_length=30),
        ),
    ]
